name: Build LaTeX document
on:
  push:
    branches:
      - main 
    paths-ignore:
      - '**.pdf'
  workflow_dispatch:

jobs:
  build_proposal:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile proposal LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: proposal.tex
      - name: Compile literature review LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: literature_review.tex
      - name: Compile experimental methodology LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: experimental_methodology.tex
      - name: Compile final LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: final.tex
      - name: Get current timestamp
        id: timestamp
        run: echo "timestamp=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV
      
      # - name: Create GitHub Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     tag_name: release-${{ env.timestamp }}
      #     name: Release ${{ env.timestamp }}
      #     draft: false
      #     prerelease: false
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      
      - name: Upload PDF to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            proposal.pdf
            literature_review.pdf
            experimental_methodology.pdf
            final.pdf
          tag_name: release-${{ env.timestamp }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
